name: smartdine_queue_manager
description: Flutter Web App for smartDine queue manager.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # api call
  dio: ^5.2.1+1

  # state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  #dependency injection
  get_it: ^7.6.0

  # error handling
  dartz: ^0.10.1

  # routing
  fluro: ^2.0.5

  # utils
  intl: 0.18.0
  uuid: ^3.0.5

  # flavors environment setup
  flutter_dotenv: ^5.0.2

  # for phone call
  flutter_phone_direct_caller: 2.1.1

  # firebase
  firebase_core: 2.13.1
  firebase_storage: 11.2.2
  cloud_firestore: 4.8.0

  # ui
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.5

flutter:

  generate: true
  uses-material-design: true

  assets:
    - dev.env
    - prod.env
    - assets/images/light_theme/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
